#! /bin/sh

. ~/scripts/theme_config

# config options
bspc config border_width            2
#bspc config top_padding             22
bspc config window_gap              50
bspc config split_ratio             0.50
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config focus_follows_pointer   true

export LANG=en_US.UTF-8

# bspwm FIFO
export PANEL_FIFO="/tmp/panel_fifo"

# desktops
bspc monitor DVI-I-1 -d one two thr fou fiv
bspc monitor HDMI-0 -d tel

# Rules
bspc rule -a Gimp desktop=^4
bspc rule -a imv desktop=^2
bspc rule -a Gimp-2.8 desktop=^4
bspc rule -a Transmission-gtk desktop=^5
bspc rule -a Lxappearance state=floating center=true
bspc rule -a Nitrogen state=floating center=true
bspc rule -a File-roller state=floating center=true

# colors
bspc config focused_border_color ${focused_border_color}
bspc config normal_border_color ${normal_border_color}
bspc config active_border_color ${active_border_color}
bspc config presel_feedback_color ${presel_color}

# Autostart apps
stalonetray &
firefox &
xsetroot -cursor_name left_ptr &
album &
nm-applet &
sh panel.sh &

