#! /bin/sh

source "$HOME/.cache/wal/colors.sh"

# config options
bspc config border_width            2
#bspc config top_padding             22
bspc config window_gap              50
bspc config split_ratio             0.50
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config focus_follows_pointer   true

export LANG=en_US.UTF-8

# bspwm FIFO
export PANEL_FIFO="/tmp/panel_fifo"

# desktops
bspc monitor DVI-I-1 -d one two thr fou fiv
bspc monitor HDMI-0 -d tel

# Rules
bspc rule -a feh:album desktop='^2'
bspc rule -a urxvt:ncmpcpp desktop='^2'
bspc config external_rules_command "$(which external_rules)"

# colors
bspc config focused_border_color $(color15)
bspc config normal_border_color $(color15)
bspc config active_border_color $(color0)
bspc config presel_feedback_color $(color10)

# Autostart apps
xsetroot -cursor_name left_ptr &

