#!/bin/bash

# Display current album art with feh

COVER="/home/brandon/.cache/cover.png"
GEOMETRY="980x980+470+50"
CURRENT_DIR="/home/brandon/Music"
CURRENT_FILE="$(mpc current -f "%file%")"
VALUE=$(pgrep -cx feh )

while true;:
do
CURRENT_FILE="$(mpc current -f "%file%")"
sleep 5;
ffmpeg -y -i "$CURRENT_DIR/$CURRENT_FILE" $COVER

done

#while true [mpc status | grep -F "[playing]"]
#do
#    ffmpeg -i "$CURRENT_DIR/$CURRENT_FILE" $COVER
#    echo "changed art"
#done

if [ $VALUE -eq 0 ]
then
  feh -Z --title "album" -x -R 5 -g "$GEOMETRY" "$COVER"
else
  :
fi

